"""Card colors, color-pair names, deck filters, and tkinter row-tag styling.

Colors must stay WUBRG-sorted: dictionary lookups and the WUBRG event-string
normalization both depend on it.
"""

from src.constants.data_fields import FILTER_OPTION_ALL_DECKS, FILTER_OPTION_AUTO
from src.constants.ui import FONT_SANS_SERIF

CARD_COLOR_SYMBOL_WHITE = "W"
CARD_COLOR_SYMBOL_BLACK = "B"
CARD_COLOR_SYMBOL_BLUE = "U"
CARD_COLOR_SYMBOL_RED = "R"
CARD_COLOR_SYMBOL_GREEN = "G"
CARD_COLOR_SYMBOL_NONE = "NC"

CARD_COLORS = [
    CARD_COLOR_SYMBOL_WHITE,
    CARD_COLOR_SYMBOL_BLUE,
    CARD_COLOR_SYMBOL_BLACK,
    CARD_COLOR_SYMBOL_RED,
    CARD_COLOR_SYMBOL_GREEN,
]

CARD_COLOR_LABEL_WHITE = "White"
CARD_COLOR_LABEL_BLACK = "Black"
CARD_COLOR_LABEL_BLUE = "Blue"
CARD_COLOR_LABEL_RED = "Red"
CARD_COLOR_LABEL_GREEN = "Green"
CARD_COLOR_LABEL_NC = "NC"

COLOR_NAMES_DICT = {
    CARD_COLOR_SYMBOL_WHITE: CARD_COLOR_LABEL_WHITE,
    CARD_COLOR_SYMBOL_BLUE: CARD_COLOR_LABEL_BLUE,
    CARD_COLOR_SYMBOL_BLACK: CARD_COLOR_LABEL_BLACK,
    CARD_COLOR_SYMBOL_RED: CARD_COLOR_LABEL_RED,
    CARD_COLOR_SYMBOL_GREEN: CARD_COLOR_LABEL_GREEN,
    "WU": "Azorius",
    "UB": "Dimir",
    "BR": "Rakdos",
    "RG": "Gruul",
    "WG": "Selesnya",
    "WB": "Orzhov",
    "BG": "Golgari",
    "UG": "Simic",
    "UR": "Izzet",
    "WR": "Boros",
    "WUR": "Jeskai",
    "UBG": "Sultai",
    "WBR": "Mardu",
    "URG": "Temur",
    "WBG": "Abzan",
    "WUB": "Esper",
    "UBR": "Grixis",
    "BRG": "Jund",
    "WRG": "Naya",
    "WUG": "Bant",
    "WUBR": "Not-Green",
    "UBRG": "Not-White",
    "WBRG": "Not-Blue",
    "WURG": "Not-Black",
    "WUBG": "Not-Red",
    "WUBRG": "Five-Color",
}
DECK_COLORS = [FILTER_OPTION_ALL_DECKS] + [k for k in COLOR_NAMES_DICT.keys()]
DECK_FILTERS = [FILTER_OPTION_AUTO] + DECK_COLORS

CARD_COLORS_DICT = {
    CARD_COLOR_LABEL_WHITE: CARD_COLOR_SYMBOL_WHITE,
    CARD_COLOR_LABEL_BLACK: CARD_COLOR_SYMBOL_BLACK,
    CARD_COLOR_LABEL_BLUE: CARD_COLOR_SYMBOL_BLUE,
    CARD_COLOR_LABEL_RED: CARD_COLOR_SYMBOL_RED,
    CARD_COLOR_LABEL_GREEN: CARD_COLOR_SYMBOL_GREEN,
    CARD_COLOR_LABEL_NC: "",
}

BW_ROW_COLOR_ODD_TAG = "bw_odd"
BW_ROW_COLOR_EVEN_TAG = "bw_even"
CARD_ROW_COLOR_WHITE_TAG = "white_card"
CARD_ROW_COLOR_RED_TAG = "red_card"
CARD_ROW_COLOR_BLUE_TAG = "blue_card"
CARD_ROW_COLOR_BLACK_TAG = "black_card"
CARD_ROW_COLOR_GREEN_TAG = "green_card"
CARD_ROW_COLOR_GOLD_TAG = "gold_card"
CARD_ROW_COLOR_COLORLESS_TAG = "colorless_card"

ROW_TAGS_BW_DICT = {
    BW_ROW_COLOR_ODD_TAG: (FONT_SANS_SERIF, "#3d3d3d", "#e6ecec"),
    BW_ROW_COLOR_EVEN_TAG: (FONT_SANS_SERIF, "#333333", "#e6ecec"),
}

ROW_TAGS_COLORS_DICT = {
    CARD_ROW_COLOR_WHITE_TAG: (FONT_SANS_SERIF, "#E9E9E9", "#000000"),
    CARD_ROW_COLOR_RED_TAG: (FONT_SANS_SERIF, "#FF6C6C", "#000000"),
    CARD_ROW_COLOR_BLUE_TAG: (FONT_SANS_SERIF, "#6078c6", "#000000"),
    CARD_ROW_COLOR_BLACK_TAG: (FONT_SANS_SERIF, "#BFBFBF", "#000000"),
    CARD_ROW_COLOR_GREEN_TAG: (FONT_SANS_SERIF, "#60BC68", "#000000"),
    CARD_ROW_COLOR_GOLD_TAG: (FONT_SANS_SERIF, "#F0BE26", "#000000"),
    CARD_ROW_COLOR_COLORLESS_TAG: (FONT_SANS_SERIF, "#8e9eae", "#000000"),
}

__all__ = [
    "CARD_COLOR_SYMBOL_WHITE",
    "CARD_COLOR_SYMBOL_BLACK",
    "CARD_COLOR_SYMBOL_BLUE",
    "CARD_COLOR_SYMBOL_RED",
    "CARD_COLOR_SYMBOL_GREEN",
    "CARD_COLOR_SYMBOL_NONE",
    "CARD_COLORS",
    "CARD_COLOR_LABEL_WHITE",
    "CARD_COLOR_LABEL_BLACK",
    "CARD_COLOR_LABEL_BLUE",
    "CARD_COLOR_LABEL_RED",
    "CARD_COLOR_LABEL_GREEN",
    "CARD_COLOR_LABEL_NC",
    "COLOR_NAMES_DICT",
    "DECK_COLORS",
    "DECK_FILTERS",
    "CARD_COLORS_DICT",
    "BW_ROW_COLOR_ODD_TAG",
    "BW_ROW_COLOR_EVEN_TAG",
    "CARD_ROW_COLOR_WHITE_TAG",
    "CARD_ROW_COLOR_RED_TAG",
    "CARD_ROW_COLOR_BLUE_TAG",
    "CARD_ROW_COLOR_BLACK_TAG",
    "CARD_ROW_COLOR_GREEN_TAG",
    "CARD_ROW_COLOR_GOLD_TAG",
    "CARD_ROW_COLOR_COLORLESS_TAG",
    "ROW_TAGS_BW_DICT",
    "ROW_TAGS_COLORS_DICT",
]
