"""Local MTGA SQLite schema: file prefixes, tables, columns, queries, card keys.

Used by src/file_extractor.py to resolve GrpId -> card data from the game's
local database.
"""

LOCAL_DATA_FILE_PREFIX_CARDS = "Raw_cards_"
LOCAL_DATA_FILE_PREFIX_DATABASE = "Raw_CardDatabase_"

LOCAL_DATABASE_TABLE_LOCALIZATION = "Localizations_enUS"
LOCAL_DATABASE_TABLE_ENUMERATOR = "Enums"
LOCAL_DATABASE_TABLE_CARDS = "Cards"

LOCAL_DATABASE_LOCALIZATION_COLUMN_ID = "LocId"
LOCAL_DATABASE_LOCALIZATION_COLUMN_FORMAT = "Formatted"
LOCAL_DATABASE_LOCALIZATION_COLUMN_TEXT = "Loc"

LOCAL_DATABASE_ENUMERATOR_COLUMN_ID = "LocId"
LOCAL_DATABASE_ENUMERATOR_COLUMN_TYPE = "Type"
LOCAL_DATABASE_ENUMERATOR_COLUMN_VALUE = "Value"

LOCAL_DATABASE_ENUMERATOR_TYPE_COLOR = "Color"
LOCAL_DATABASE_ENUMERATOR_TYPE_CARD_TYPES = "CardType"

LOCAL_DATABASE_LOCALIZATION_QUERY = f"""SELECT
                                            A.{LOCAL_DATABASE_LOCALIZATION_COLUMN_ID}, 
                                            A.{LOCAL_DATABASE_LOCALIZATION_COLUMN_FORMAT}, 
                                            A.{LOCAL_DATABASE_LOCALIZATION_COLUMN_TEXT}
                                        FROM {LOCAL_DATABASE_TABLE_LOCALIZATION} A INNER JOIN(
                                            SELECT 
                                                {LOCAL_DATABASE_LOCALIZATION_COLUMN_ID},
                                                min({LOCAL_DATABASE_LOCALIZATION_COLUMN_FORMAT}) AS MIN_FORMAT 
                                            FROM {LOCAL_DATABASE_TABLE_LOCALIZATION} 
                                            GROUP BY {LOCAL_DATABASE_LOCALIZATION_COLUMN_ID}) 
                                        B ON A.{LOCAL_DATABASE_LOCALIZATION_COLUMN_ID} = B.{LOCAL_DATABASE_LOCALIZATION_COLUMN_ID} 
                                        AND A.{LOCAL_DATABASE_LOCALIZATION_COLUMN_FORMAT} = B.MIN_FORMAT"""

LOCAL_DATABASE_ENUMERATOR_QUERY = f"""SELECT
                                        {LOCAL_DATABASE_ENUMERATOR_COLUMN_ID},
                                        {LOCAL_DATABASE_ENUMERATOR_COLUMN_TYPE},
                                        {LOCAL_DATABASE_ENUMERATOR_COLUMN_VALUE}
                                      FROM {LOCAL_DATABASE_TABLE_ENUMERATOR}
                                      WHERE {LOCAL_DATABASE_ENUMERATOR_COLUMN_TYPE} 
                                      IN ('{LOCAL_DATABASE_ENUMERATOR_TYPE_COLOR}', 
                                          '{LOCAL_DATABASE_ENUMERATOR_TYPE_CARD_TYPES}', 
                                          'SubType')"""

LOCAL_DATABASE_CARDS_QUERY = f"SELECT * FROM {LOCAL_DATABASE_TABLE_CARDS}"

LOCAL_CARDS_KEY_SET = "expansioncode"
LOCAL_CARDS_KEY_DIGITAL_RELEASE_SET = "digitalreleaseset"
LOCAL_CARDS_KEY_GROUP_ID = "grpid"
LOCAL_CARDS_KEY_TOKEN = "istoken"
LOCAL_CARDS_KEY_LINKED_FACES = "linkedfacegrpids"
LOCAL_CARDS_KEY_LINKED_FACE_TYPE = "linkedfacetype"
LOCAL_CARDS_KEY_TYPES = "types"
LOCAL_CARDS_KEY_TITLE_ID = "titleid"
LOCAL_CARDS_KEY_CMC = "cmc"
LOCAL_CARDS_KEY_COLOR_ID = "coloridentity"
LOCAL_CARDS_KEY_CASTING_COST = "oldschoolmanatext"
LOCAL_CARDS_KEY_RARITY = "rarity"
LOCAL_CARDS_KEY_PRIMARY = "isprimarycard"

__all__ = [
    "LOCAL_DATA_FILE_PREFIX_CARDS",
    "LOCAL_DATA_FILE_PREFIX_DATABASE",
    "LOCAL_DATABASE_TABLE_LOCALIZATION",
    "LOCAL_DATABASE_TABLE_ENUMERATOR",
    "LOCAL_DATABASE_TABLE_CARDS",
    "LOCAL_DATABASE_LOCALIZATION_COLUMN_ID",
    "LOCAL_DATABASE_LOCALIZATION_COLUMN_FORMAT",
    "LOCAL_DATABASE_LOCALIZATION_COLUMN_TEXT",
    "LOCAL_DATABASE_ENUMERATOR_COLUMN_ID",
    "LOCAL_DATABASE_ENUMERATOR_COLUMN_TYPE",
    "LOCAL_DATABASE_ENUMERATOR_COLUMN_VALUE",
    "LOCAL_DATABASE_ENUMERATOR_TYPE_COLOR",
    "LOCAL_DATABASE_ENUMERATOR_TYPE_CARD_TYPES",
    "LOCAL_DATABASE_LOCALIZATION_QUERY",
    "LOCAL_DATABASE_ENUMERATOR_QUERY",
    "LOCAL_DATABASE_CARDS_QUERY",
    "LOCAL_CARDS_KEY_SET",
    "LOCAL_CARDS_KEY_DIGITAL_RELEASE_SET",
    "LOCAL_CARDS_KEY_GROUP_ID",
    "LOCAL_CARDS_KEY_TOKEN",
    "LOCAL_CARDS_KEY_LINKED_FACES",
    "LOCAL_CARDS_KEY_LINKED_FACE_TYPE",
    "LOCAL_CARDS_KEY_TYPES",
    "LOCAL_CARDS_KEY_TITLE_ID",
    "LOCAL_CARDS_KEY_CMC",
    "LOCAL_CARDS_KEY_COLOR_ID",
    "LOCAL_CARDS_KEY_CASTING_COST",
    "LOCAL_CARDS_KEY_RARITY",
    "LOCAL_CARDS_KEY_PRIMARY",
]
