"""17Lands / dataset field names, labels, filter options, and time periods."""

COLOR_WIN_RATE_GAME_COUNT_THRESHOLD_DEFAULT = 500

DATA_FIELD_17LANDS_OHWR = "opening_hand_win_rate"
DATA_FIELD_17LANDS_NGOH = "opening_hand_game_count"
DATA_FIELD_17LANDS_GPWR = "win_rate"
DATA_FIELD_17LANDS_NGP = "game_count"
DATA_FIELD_17LANDS_GIHWR = "ever_drawn_win_rate"
DATA_FIELD_17LANDS_IWD = "drawn_improvement_win_rate"
DATA_FIELD_17LANDS_ALSA = "avg_seen"
DATA_FIELD_17LANDS_GIH = "ever_drawn_game_count"
DATA_FIELD_17LANDS_ATA = "avg_pick"
DATA_FIELD_17LANDS_NGND = "never_drawn_game_count"
DATA_FIELD_17LANDS_GNSWR = "never_drawn_win_rate"
DATA_FIELD_17LANDS_GDWR = "drawn_win_rate"
DATA_FIELD_17LANDS_NGD = "drawn_game_count"
DATA_FIELD_17LANDS_IMAGE = "url"
DATA_FIELD_17LANDS_IMAGE_BACK = "url_back"

DATA_FIELD_GIHWR = "gihwr"
DATA_FIELD_OHWR = "ohwr"
DATA_FIELD_GPWR = "gpwr"
DATA_FIELD_ALSA = "alsa"
DATA_FIELD_IWD = "iwd"
DATA_FIELD_ATA = "ata"
DATA_FIELD_NGP = "ngp"
DATA_FIELD_NGOH = "ngoh"
DATA_FIELD_GIH = "gih"
DATA_FIELD_GNSWR = "gnswr"
DATA_FIELD_NGND = "ngnd"
DATA_FIELD_GDWR = "gdwr"
DATA_FIELD_NGD = "ngd"
DATA_FIELD_WHEEL = "wheel"

DATA_SECTION_IMAGES = "image"
DATA_SECTION_RATINGS = "ratings"

DATA_FIELD_CMC = "cmc"
DATA_FIELD_COLORS = "colors"
DATA_FIELD_NAME = "name"
DATA_FIELD_TYPES = "types"
DATA_FIELD_DECK_COLORS = "deck_colors"
DATA_FIELD_COUNT = "count"
DATA_FIELD_DISABLED = "disabled"
DATA_FIELD_RARITY = "rarity"
DATA_FIELD_MANA_COST = "mana_cost"
DATA_FIELD_SUBTYPES = "subtypes"
DATA_FIELD_ORACLE_TEXT = "oracle_text"

DATA_FIELDS_LIST = [
    DATA_FIELD_GIHWR,
    DATA_FIELD_OHWR,
    DATA_FIELD_GPWR,
    DATA_FIELD_GNSWR,
    DATA_FIELD_ALSA,
    DATA_FIELD_ATA,
    DATA_FIELD_IWD,
    DATA_FIELD_NGP,
    DATA_FIELD_NGOH,
    DATA_FIELD_GIH,
    DATA_FIELD_NGND,
    DATA_FIELD_GDWR,
    DATA_FIELD_NGD,
]

DATA_SET_FIELDS = [
    DATA_FIELD_GIHWR,
    DATA_FIELD_OHWR,
    DATA_FIELD_GPWR,
    DATA_FIELD_ALSA,
    DATA_FIELD_IWD,
    DATA_FIELD_CMC,
    DATA_FIELD_COLORS,
    DATA_FIELD_NAME,
    DATA_FIELD_TYPES,
    DATA_FIELD_MANA_COST,
    DATA_SECTION_IMAGES,
    DATA_FIELD_DECK_COLORS,
]

FILTER_OPTION_ALL_DECKS = "All Decks"
FILTER_OPTION_AUTO = "Auto"
FILTER_OPTION_TIER = "TIER"

FIELD_LABEL_ATA = "ATA: Average Taken At"
FIELD_LABEL_ALSA = "ALSA: Average Last Seen At"
FIELD_LABEL_IWD = "IWD: Improvement When Drawn"
FIELD_LABEL_OHWR = "OHWR: Opening Hand Win Rate"
FIELD_LABEL_GPWR = "GPWR: Games Played Win Rate"
FIELD_LABEL_GIHWR = "GIHWR: Games In Hand Win Rate"
FIELD_LABEL_GNSWR = "GNSWR: Games Not Seen Win Rate"
FIELD_LABEL_COLORS = "COLORS: Card Colors"
FIELD_LABEL_DISABLED = "DISABLED: Remove Column"
FIELD_LABEL_COUNT = "COUNT: Total Card Count"
FIELD_LABEL_WHEEL = "WHEEL: Probability of Wheeling"
FIELD_LABEL_GDWR = "GDWR: Games Drawn Win Rate"

DATA_SET_VERSION_3 = 3.0

START_DATE_DEFAULT = "2019-01-01"

WIN_RATE_OPTIONS = [
    DATA_FIELD_GIHWR,
    DATA_FIELD_OHWR,
    DATA_FIELD_GPWR,
    DATA_FIELD_GNSWR,
    DATA_FIELD_GDWR,
]
NON_COLORS_OPTIONS = WIN_RATE_OPTIONS + [
    DATA_FIELD_IWD,
    DATA_FIELD_ALSA,
    DATA_FIELD_ATA,
]
COLUMN_OPTIONS = NON_COLORS_OPTIONS

COLUMN_FIELD_LABELS = {
    "gihwr": "GIH WR: Games in Hand Win Rate",
    "ohwr": "OH WR: Opening Hand Win Rate",
    "gpwr": "GP WR: Games Played Win Rate",
    "alsa": "ALSA: Average Last Seen At",
    "ata": "ATA: Average Taken At",
    "iwd": "IWD: Improvement When Drawn",
    "wheel": "WHEEL: Probability of Wheeling",
    "colors": "COLORS: Card Colors",
    "count": "COUNT: Total Card Count",
    "value": "VALUE: Advisor Tactical Score",
    "tags": "TAGS: Card Roles",
}
LABEL_TO_COLUMN_FIELD = {v: k for k, v in COLUMN_FIELD_LABELS.items()}

DECK_FILTER_DEFAULT = FILTER_OPTION_AUTO

DATA_SOURCES_NONE = {"None": ""}

DEFAULT_GIHWR_AVERAGE = 0.0

DATA_FIELD_TAGS = "tags"

WIN_RATE_FIELDS_DICT = {
    DATA_FIELD_GIHWR: DATA_FIELD_GIH,
    DATA_FIELD_OHWR: DATA_FIELD_NGOH,
    DATA_FIELD_GPWR: DATA_FIELD_NGP,
    DATA_FIELD_GNSWR: DATA_FIELD_NGND,
    DATA_FIELD_GDWR: DATA_FIELD_NGD,
}

DATA_FIELD_17LANDS_DICT = {
    DATA_FIELD_GIHWR: DATA_FIELD_17LANDS_GIHWR,
    DATA_FIELD_OHWR: DATA_FIELD_17LANDS_OHWR,
    DATA_FIELD_GPWR: DATA_FIELD_17LANDS_GPWR,
    DATA_FIELD_ALSA: DATA_FIELD_17LANDS_ALSA,
    DATA_FIELD_IWD: DATA_FIELD_17LANDS_IWD,
    DATA_FIELD_ATA: DATA_FIELD_17LANDS_ATA,
    DATA_FIELD_NGP: DATA_FIELD_17LANDS_NGP,
    DATA_FIELD_NGOH: DATA_FIELD_17LANDS_NGOH,
    DATA_FIELD_GIH: DATA_FIELD_17LANDS_GIH,
    DATA_FIELD_GNSWR: DATA_FIELD_17LANDS_GNSWR,
    DATA_FIELD_NGND: DATA_FIELD_17LANDS_NGND,
    DATA_FIELD_GDWR: DATA_FIELD_17LANDS_GDWR,
    DATA_FIELD_NGD: DATA_FIELD_17LANDS_NGD,
    DATA_SECTION_IMAGES: [DATA_FIELD_17LANDS_IMAGE, DATA_FIELD_17LANDS_IMAGE_BACK],
}

COLUMNS_OPTIONS_MAIN_DICT = {
    FIELD_LABEL_ATA: DATA_FIELD_ATA,
    FIELD_LABEL_ALSA: DATA_FIELD_ALSA,
    FIELD_LABEL_IWD: DATA_FIELD_IWD,
    FIELD_LABEL_OHWR: DATA_FIELD_OHWR,
    FIELD_LABEL_GPWR: DATA_FIELD_GPWR,
    FIELD_LABEL_GIHWR: DATA_FIELD_GIHWR,
    FIELD_LABEL_GDWR: DATA_FIELD_GDWR,
    FIELD_LABEL_GNSWR: DATA_FIELD_GNSWR,
    FIELD_LABEL_WHEEL: DATA_FIELD_WHEEL,
    FIELD_LABEL_COLORS: DATA_FIELD_COLORS,
}

COLUMNS_OPTIONS_EXTRA_DICT = {
    FIELD_LABEL_DISABLED: DATA_FIELD_DISABLED,
    FIELD_LABEL_ATA: DATA_FIELD_ATA,
    FIELD_LABEL_ALSA: DATA_FIELD_ALSA,
    FIELD_LABEL_IWD: DATA_FIELD_IWD,
    FIELD_LABEL_OHWR: DATA_FIELD_OHWR,
    FIELD_LABEL_GPWR: DATA_FIELD_GPWR,
    FIELD_LABEL_GIHWR: DATA_FIELD_GIHWR,
    FIELD_LABEL_GDWR: DATA_FIELD_GDWR,
    FIELD_LABEL_GNSWR: DATA_FIELD_GNSWR,
    FIELD_LABEL_WHEEL: DATA_FIELD_WHEEL,
    FIELD_LABEL_COLORS: DATA_FIELD_COLORS,
}

# 17Lands replaced custom start_date/end_date ranges with these preset
# "time_period" values (the drop-down on the card pages). Maps the UI label to
# the query value the endpoint expects; confirm against the browser Network tab
# if a preset ever stops returning data.
TIME_PERIOD_OPTIONS = {
    "All Time": "ALL_TIME",
    "Latest Event": "LATEST_EVENT",
    "Last Two Weeks": "LAST_TWO_WEEKS",
    "Last Week": "LAST_WEEK",
    "Last Day": "LAST_DAY",
    "First Week": "FIRST_WEEK",
    "All Except First Week": "ALL_EXCEPT_FIRST_WEEK",
}
TIME_PERIOD_LABELS = list(TIME_PERIOD_OPTIONS.keys())
TIME_PERIOD_DEFAULT_LABEL = "All Time"
TIME_PERIOD_DEFAULT = "ALL_TIME"


def time_period_value(label: str) -> str:
    """UI label -> 17Lands query value, falling back to All Time."""
    return TIME_PERIOD_OPTIONS.get(label, TIME_PERIOD_DEFAULT)


def time_period_label(value: str) -> str:
    """17Lands query value -> UI label, falling back to All Time."""
    for lbl, val in TIME_PERIOD_OPTIONS.items():
        if val == value:
            return lbl
    return TIME_PERIOD_DEFAULT_LABEL


__all__ = [
    "COLOR_WIN_RATE_GAME_COUNT_THRESHOLD_DEFAULT",
    "DATA_FIELD_17LANDS_OHWR",
    "DATA_FIELD_17LANDS_NGOH",
    "DATA_FIELD_17LANDS_GPWR",
    "DATA_FIELD_17LANDS_NGP",
    "DATA_FIELD_17LANDS_GIHWR",
    "DATA_FIELD_17LANDS_IWD",
    "DATA_FIELD_17LANDS_ALSA",
    "DATA_FIELD_17LANDS_GIH",
    "DATA_FIELD_17LANDS_ATA",
    "DATA_FIELD_17LANDS_NGND",
    "DATA_FIELD_17LANDS_GNSWR",
    "DATA_FIELD_17LANDS_GDWR",
    "DATA_FIELD_17LANDS_NGD",
    "DATA_FIELD_17LANDS_IMAGE",
    "DATA_FIELD_17LANDS_IMAGE_BACK",
    "DATA_FIELD_GIHWR",
    "DATA_FIELD_OHWR",
    "DATA_FIELD_GPWR",
    "DATA_FIELD_ALSA",
    "DATA_FIELD_IWD",
    "DATA_FIELD_ATA",
    "DATA_FIELD_NGP",
    "DATA_FIELD_NGOH",
    "DATA_FIELD_GIH",
    "DATA_FIELD_GNSWR",
    "DATA_FIELD_NGND",
    "DATA_FIELD_GDWR",
    "DATA_FIELD_NGD",
    "DATA_FIELD_WHEEL",
    "DATA_SECTION_IMAGES",
    "DATA_SECTION_RATINGS",
    "DATA_FIELD_CMC",
    "DATA_FIELD_COLORS",
    "DATA_FIELD_NAME",
    "DATA_FIELD_TYPES",
    "DATA_FIELD_DECK_COLORS",
    "DATA_FIELD_COUNT",
    "DATA_FIELD_DISABLED",
    "DATA_FIELD_RARITY",
    "DATA_FIELD_MANA_COST",
    "DATA_FIELD_SUBTYPES",
    "DATA_FIELD_ORACLE_TEXT",
    "DATA_FIELDS_LIST",
    "DATA_SET_FIELDS",
    "FILTER_OPTION_ALL_DECKS",
    "FILTER_OPTION_AUTO",
    "FILTER_OPTION_TIER",
    "FIELD_LABEL_ATA",
    "FIELD_LABEL_ALSA",
    "FIELD_LABEL_IWD",
    "FIELD_LABEL_OHWR",
    "FIELD_LABEL_GPWR",
    "FIELD_LABEL_GIHWR",
    "FIELD_LABEL_GNSWR",
    "FIELD_LABEL_COLORS",
    "FIELD_LABEL_DISABLED",
    "FIELD_LABEL_COUNT",
    "FIELD_LABEL_WHEEL",
    "FIELD_LABEL_GDWR",
    "DATA_SET_VERSION_3",
    "START_DATE_DEFAULT",
    "WIN_RATE_OPTIONS",
    "NON_COLORS_OPTIONS",
    "COLUMN_OPTIONS",
    "COLUMN_FIELD_LABELS",
    "LABEL_TO_COLUMN_FIELD",
    "DECK_FILTER_DEFAULT",
    "DATA_SOURCES_NONE",
    "DEFAULT_GIHWR_AVERAGE",
    "DATA_FIELD_TAGS",
    "WIN_RATE_FIELDS_DICT",
    "DATA_FIELD_17LANDS_DICT",
    "COLUMNS_OPTIONS_MAIN_DICT",
    "COLUMNS_OPTIONS_EXTRA_DICT",
    "TIME_PERIOD_OPTIONS",
    "TIME_PERIOD_LABELS",
    "TIME_PERIOD_DEFAULT_LABEL",
    "TIME_PERIOD_DEFAULT",
    "time_period_value",
    "time_period_label",
]
