"""Limited-format type ids, their log strings, and user-group filters."""

LIMITED_TYPE_UNKNOWN = 0
LIMITED_TYPE_DRAFT_PREMIER_V1 = 1
LIMITED_TYPE_DRAFT_PREMIER_V2 = 2
LIMITED_TYPE_DRAFT_QUICK = 3
LIMITED_TYPE_DRAFT_TRADITIONAL = 4
LIMITED_TYPE_SEALED = 5
LIMITED_TYPE_SEALED_TRADITIONAL = 6
LIMITED_TYPE_DRAFT_PICK_TWO = 7
LIMITED_TYPE_DRAFT_PICK_TWO_TRAD = 8
LIMITED_TYPE_DRAFT_PICK_TWO_QUICK = 9
LIMITED_TYPE_DRAFT_CONTENDER = 10

LIMITED_TYPE_STRING_DRAFT_PREMIER = "PremierDraft"
LIMITED_TYPE_STRING_DRAFT_QUICK = "QuickDraft"
LIMITED_TYPE_STRING_DRAFT_BOT = "BotDraft"
LIMITED_TYPE_STRING_DRAFT_TRAD = "TradDraft"
LIMITED_TYPE_STRING_SEALED = "Sealed"
LIMITED_TYPE_STRING_TRAD_SEALED = "TradSealed"
LIMITED_TYPE_STRING_DRAFT_PICK_TWO = "PickTwoDraft"
LIMITED_TYPE_STRING_DRAFT_PICK_TWO_TRAD = "PickTwoTradDraft"
LIMITED_TYPE_STRING_DRAFT_PICK_TWO_QUICK = "PickTwoQuickDraft"
LIMITED_TYPE_STRING_DRAFT_CONTENDER = "ContenderDraft"

LIMITED_TYPE_LIST = [
    LIMITED_TYPE_STRING_DRAFT_PREMIER,
    LIMITED_TYPE_STRING_DRAFT_QUICK,
    LIMITED_TYPE_STRING_DRAFT_TRAD,
    LIMITED_TYPE_STRING_SEALED,
    LIMITED_TYPE_STRING_TRAD_SEALED,
    LIMITED_TYPE_STRING_DRAFT_PICK_TWO,
    LIMITED_TYPE_STRING_DRAFT_PICK_TWO_TRAD,
    LIMITED_TYPE_STRING_DRAFT_CONTENDER,
]

# Used to identify the limited type based on log string
LIMITED_TYPES_DICT = {
    LIMITED_TYPE_STRING_DRAFT_PREMIER: LIMITED_TYPE_DRAFT_PREMIER_V2,  # UPDATED to V2
    LIMITED_TYPE_STRING_DRAFT_QUICK: LIMITED_TYPE_DRAFT_QUICK,
    LIMITED_TYPE_STRING_DRAFT_TRAD: LIMITED_TYPE_DRAFT_TRADITIONAL,
    LIMITED_TYPE_STRING_DRAFT_BOT: LIMITED_TYPE_DRAFT_QUICK,
    LIMITED_TYPE_STRING_SEALED: LIMITED_TYPE_SEALED,
    LIMITED_TYPE_STRING_TRAD_SEALED: LIMITED_TYPE_SEALED_TRADITIONAL,
    LIMITED_TYPE_STRING_DRAFT_PICK_TWO: LIMITED_TYPE_DRAFT_PICK_TWO,
    LIMITED_TYPE_STRING_DRAFT_PICK_TWO_TRAD: LIMITED_TYPE_DRAFT_PICK_TWO_TRAD,
    LIMITED_TYPE_STRING_DRAFT_PICK_TWO_QUICK: LIMITED_TYPE_DRAFT_PICK_TWO_QUICK,
    LIMITED_TYPE_STRING_DRAFT_CONTENDER: LIMITED_TYPE_DRAFT_CONTENDER,
}

LIMITED_USER_GROUP_ALL = "All"
LIMITED_USER_GROUP_BOTTOM = "Bottom"
LIMITED_USER_GROUP_MIDDLE = "Middle"
LIMITED_USER_GROUP_TOP = "Top"

LIMITED_GROUPS_LIST = [
    LIMITED_USER_GROUP_ALL,
    LIMITED_USER_GROUP_TOP,
    LIMITED_USER_GROUP_MIDDLE,
    LIMITED_USER_GROUP_BOTTOM,
]

__all__ = [
    "LIMITED_TYPE_UNKNOWN",
    "LIMITED_TYPE_DRAFT_PREMIER_V1",
    "LIMITED_TYPE_DRAFT_PREMIER_V2",
    "LIMITED_TYPE_DRAFT_QUICK",
    "LIMITED_TYPE_DRAFT_TRADITIONAL",
    "LIMITED_TYPE_SEALED",
    "LIMITED_TYPE_SEALED_TRADITIONAL",
    "LIMITED_TYPE_DRAFT_PICK_TWO",
    "LIMITED_TYPE_DRAFT_PICK_TWO_TRAD",
    "LIMITED_TYPE_DRAFT_PICK_TWO_QUICK",
    "LIMITED_TYPE_DRAFT_CONTENDER",
    "LIMITED_TYPE_STRING_DRAFT_PREMIER",
    "LIMITED_TYPE_STRING_DRAFT_QUICK",
    "LIMITED_TYPE_STRING_DRAFT_BOT",
    "LIMITED_TYPE_STRING_DRAFT_TRAD",
    "LIMITED_TYPE_STRING_SEALED",
    "LIMITED_TYPE_STRING_TRAD_SEALED",
    "LIMITED_TYPE_STRING_DRAFT_PICK_TWO",
    "LIMITED_TYPE_STRING_DRAFT_PICK_TWO_TRAD",
    "LIMITED_TYPE_STRING_DRAFT_PICK_TWO_QUICK",
    "LIMITED_TYPE_STRING_DRAFT_CONTENDER",
    "LIMITED_TYPE_LIST",
    "LIMITED_TYPES_DICT",
    "LIMITED_USER_GROUP_ALL",
    "LIMITED_USER_GROUP_BOTTOM",
    "LIMITED_USER_GROUP_MIDDLE",
    "LIMITED_USER_GROUP_TOP",
    "LIMITED_GROUPS_LIST",
]
