"""Set metadata: types, source lists, selection options, offsets."""

SET_FILE_SUFFIX = "Data.json"

SET_TYPE_EXPANSION = "expansion"
SET_TYPE_ALCHEMY = "alchemy"
SET_TYPE_MASTERS = "masters"
SET_TYPE_MASTERPIECE = "masterpiece"
SET_TYPE_CORE = "core"
SET_TYPE_DRAFT_INNOVATION = "draft_innovation"

SET_LIST_ARENA = "arena"
SET_LIST_SCRYFALL = "scryfall"
SET_LIST_17LANDS = "17Lands"

SET_LIST_FIELDS = [SET_LIST_ARENA, SET_LIST_SCRYFALL, SET_LIST_17LANDS]

SET_START_DATE = "start_date"

SET_SELECTION_ALL = "ALL"
SET_SELECTION_CUBE = "CUBE"

SET_RELEASE_OFFSET_DAYS = -7
SET_LIST_COUNT_MAX = 50

SET_ARENA_CUBE_START_OFFSET_DAYS = -25

SUPPORTED_SET_TYPES = [
    SET_TYPE_EXPANSION,
    SET_TYPE_ALCHEMY,
    SET_TYPE_MASTERS,
    SET_TYPE_CORE,
    SET_TYPE_DRAFT_INNOVATION,
]

__all__ = [
    "SET_FILE_SUFFIX",
    "SET_TYPE_EXPANSION",
    "SET_TYPE_ALCHEMY",
    "SET_TYPE_MASTERS",
    "SET_TYPE_MASTERPIECE",
    "SET_TYPE_CORE",
    "SET_TYPE_DRAFT_INNOVATION",
    "SET_LIST_ARENA",
    "SET_LIST_SCRYFALL",
    "SET_LIST_17LANDS",
    "SET_LIST_FIELDS",
    "SET_START_DATE",
    "SET_SELECTION_ALL",
    "SET_SELECTION_CUBE",
    "SET_RELEASE_OFFSET_DAYS",
    "SET_LIST_COUNT_MAX",
    "SET_ARENA_CUBE_START_OFFSET_DAYS",
    "SUPPORTED_SET_TYPES",
]
